name: Nhentai Scrape and Notify Telegram Bot

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # ensure chromedriver is installed if using webdriver-manager
        pip install webdriver-manager selenium cloudscraper

    - name: Install Playwright browsers
      run: |
        playwright install --with-deps

    - name: Install Chromium for Selenium headless
      run: sudo apt-get update && sudo apt-get install -y chromium-browser

    - name: Run bot notification
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python nhentai/nhentai_bot.py

    - name: Commit and push updated old.json
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git add nhentai/data/old.json
        git diff --cached --quiet || (git commit -m "Update past.json after run" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
